SUBROUTINE ACHMT_LOAD_ALL (CDNAME)

USE LOAD_MOD, ONLY : OPEN_LOAD, CLOSE_LOAD, ILUN_IN, LOAD
IMPLICIT NONE

CHARACTER (LEN=*) :: CDNAME

LOGICAL, SAVE :: LLDONE = .FALSE.
INTEGER :: IDUM

IF (.NOT. LLDONE) THEN
  CALL OPEN_LOAD (CDNAME)
  CALL LOAD_MODD_PHY
  CALL LOAD_MODD_PHY0
  CALL LOAD_MODD_PHY1
  CALL LOAD_MODD_PHY2
  CALL LOAD_MODD_CLIM
  CALL LOAD_MODD_CST
  CALL CLOSE_LOAD
ENDIF

LLDONE = .TRUE.



CONTAINS


SUBROUTINE LOAD_MODD_PHY
USE LOAD_YOMPHY_MOD
CALL LOAD_YOMPHY(ILUN_IN)
END SUBROUTINE

SUBROUTINE LOAD_MODD_PHY0
USE LOAD_YOMPHY0_MOD
CALL LOAD_YOMPHY0(ILUN_IN)
END SUBROUTINE

SUBROUTINE LOAD_MODD_PHY1
USE LOAD_YOMPHY1_MOD
CALL LOAD_YOMPHY1(ILUN_IN)
END SUBROUTINE

SUBROUTINE LOAD_MODD_PHY2
USE LOAD_YOMPHY2_MOD
CALL LOAD_YOMPHY2(ILUN_IN)
END SUBROUTINE



SUBROUTINE LOAD_MODD_CLIM
USE YOMCLI   
CALL LOAD (ILUN_IN, STHER)
CALL LOAD (ILUN_IN, SZZ0D)
END SUBROUTINE



SUBROUTINE LOAD_MODD_CST

USE YOMCST

CALL LOAD (ILUN_IN, RPI)
CALL LOAD (ILUN_IN, RG)
CALL LOAD (ILUN_IN, RD)
CALL LOAD (ILUN_IN, RV)
CALL LOAD (ILUN_IN, RCPD)
CALL LOAD (ILUN_IN, RCPV)
CALL LOAD (ILUN_IN, RKAPPA)
CALL LOAD (ILUN_IN, RETV)
CALL LOAD (ILUN_IN, RCW)
CALL LOAD (ILUN_IN, RCS)
CALL LOAD (ILUN_IN, RLVTT)
CALL LOAD (ILUN_IN, RLSTT)
CALL LOAD (ILUN_IN, RTT)
CALL LOAD (ILUN_IN, RALPW)
CALL LOAD (ILUN_IN, RBETW)
CALL LOAD (ILUN_IN, RGAMW)
CALL LOAD (ILUN_IN, RALPS)
CALL LOAD (ILUN_IN, RBETS)
CALL LOAD (ILUN_IN, RGAMS)
CALL LOAD (ILUN_IN, RALPD)
CALL LOAD (ILUN_IN, RBETD)
CALL LOAD (ILUN_IN, RGAMD)
END SUBROUTINE


END SUBROUTINE

