MODULE SAVE_YOMPHY0_MOD

USE YOMPHY0

CONTAINS

SUBROUTINE SAVE_YOMPHY0 (KLUN)
USE SAVE_TPHY0_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LYRPHY0
LYRPHY0 = ASSOCIATED (YRPHY0)
WRITE (KLUN) LYRPHY0
IF (LYRPHY0) THEN
  CALL SAVE (KLUN, YRPHY0)
ENDIF
END SUBROUTINE

END MODULE
