MODULE SAVE_YOMPHY2_MOD

USE YOMPHY2

CONTAINS

SUBROUTINE SAVE_YOMPHY2 (KLUN)
USE SAVE_TPHY2_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LYRPHY2
LYRPHY2 = ASSOCIATED (YRPHY2)
WRITE (KLUN) LYRPHY2
IF (LYRPHY2) THEN
  CALL SAVE (KLUN, YRPHY2)
ENDIF
END SUBROUTINE

END MODULE
