MODULE SAVE_YOMPHY1_MOD

USE YOMPHY1

CONTAINS

SUBROUTINE SAVE_YOMPHY1 (KLUN)
USE SAVE_TPHY1_MOD
IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
LOGICAL :: LYRPHY1
LYRPHY1 = ASSOCIATED (YRPHY1)
WRITE (KLUN) LYRPHY1
IF (LYRPHY1) THEN
  CALL SAVE (KLUN, YRPHY1)
ENDIF
END SUBROUTINE

END MODULE
