#define ATTR_ARG

USE XRD_GETOPTIONS
USE LOAD_MOD
USE PARKIND1  ,ONLY : JPIM     ,JPRB     ,JPRD
!USE LOAD_YOMPHY_MOD
!USE LOAD_YOMPHY0_MOD
!USE LOAD_YOMPHY1_MOD
!USE LOAD_YOMPHY2_MOD


IMPLICIT NONE

INTERFACE SETALL
  PROCEDURE SETALLI1
  PROCEDURE SETALLI2
  PROCEDURE SETALLX1
  PROCEDURE SETALLX2
  PROCEDURE SETALLX3
  PROCEDURE SETALLX4
  PROCEDURE SETALLL3
END INTERFACE

INTERFACE DDIFF
  PROCEDURE DDIFFI1
  PROCEDURE DDIFFX1
  PROCEDURE DDIFFX2
  PROCEDURE DDIFFX3
  PROCEDURE DDIFFX4
END INTERFACE


!INTEGER                          :: KSV
INTEGER(KIND=JPIM)               :: KLON
INTEGER(KIND=JPIM)               :: KLEV
INTEGER(KIND=JPIM)               :: KIDIA
INTEGER(KIND=JPIM)               :: KFDIA
LOGICAL                          :: LDZ0H
LOGICAL                          :: LDCLS
LOGICAL                          :: LDHMT
!REAL(KIND=JPRB)   ,POINTER    :: PAPHI(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PAPHIF(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PAPRS(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PAPRSF(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PCP(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PQ(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PR(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PT(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PU(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PV(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PFPLSH(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PFPLCH(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PDPHIT(:)
!REAL(KIND=JPRB)   ,POINTER    :: PDPHIV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGZ0F(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGZ0HF(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGZ0RLF(:)
!REAL(KIND=JPRB)   ,POINTER    :: PHV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PLSM(:)
!REAL(KIND=JPRB)   ,POINTER    :: PNEIJG(:)
!REAL(KIND=JPRB)   ,POINTER    :: PNEIJV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PSNS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PTS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PVEG0(:)
!REAL(KIND=JPRB)   ,POINTER    :: PWFC(:)
!REAL(KIND=JPRB)   ,POINTER    :: PWS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PWSI(:)
!REAL(KIND=JPRB)   ,POINTER    :: PNBVNO(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PMRIPP(:,:)
!REAL(KIND=JPRB)   ,POINTER    :: PCD(:)
!REAL(KIND=JPRB)   ,POINTER    :: PCDN(:)
!REAL(KIND=JPRB)   ,POINTER    :: PCDROV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PCH(:)
!REAL(KIND=JPRB)   ,POINTER    :: PCHROV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PCPS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PDQSTS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGWDCS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGZ0(:)
!REAL(KIND=JPRB)   ,POINTER    :: PGZ0H(:)
!REAL(KIND=JPRB)   ,POINTER    :: PHQ(:)
!REAL(KIND=JPRB)   ,POINTER    :: PHU(:)
!REAL(KIND=JPRB)   ,POINTER    :: PNEIJ(:)
!REAL(KIND=JPRB)   ,POINTER    :: PQCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PQS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PQSATS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PRHCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PRS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PRTI(:)
!REAL(KIND=JPRB)   ,POINTER    :: PSTAB(:)
!REAL(KIND=JPRB)   ,POINTER    :: PTCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PUCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PVCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PUCLN(:)
!REAL(KIND=JPRB)   ,POINTER    :: PVCLN(:)
!REAL(KIND=JPRB)   ,POINTER    :: PZPCLS(:)
!REAL(KIND=JPRB)   ,POINTER    :: PVEG(:)
!REAL(KIND=JPRB)   ,POINTER    :: PXDROV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PXHROV(:)
!REAL(KIND=JPRB)   ,POINTER    :: PURAF(:)
!REAL(KIND=JPRB)   ,POINTER    :: PVRAF(:)


REAL(KIND=JPRB)   ,POINTER    :: PAPHI_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PAPHIF_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PAPRS_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PAPRSF_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCP_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PQ_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PR_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PT_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PU_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PV_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PFPLSH_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PFPLCH_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PDPHIT_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PDPHIV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGZ0F_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGZ0HF_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGZ0RLF_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PHV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PLSM_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PNEIJG_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PNEIJV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PSNS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PTS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PVEG0_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PWFC_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PWS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PWSI_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PNBVNO_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PMRIPP_ALL(:,:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCD_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCDN_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCDROV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCH_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCHROV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PCPS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PDQSTS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGWDCS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGZ0_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PGZ0H_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PHQ_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PHU_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PNEIJ_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PQCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PQS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PQSATS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PRHCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PRS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PRTI_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PSTAB_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PTCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PUCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PVCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PUCLN_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PVCLN_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PZPCLS_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PVEG_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PXDROV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PXHROV_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PURAF_ALL(:,:) => NULL()
REAL(KIND=JPRB)   ,POINTER    :: PVRAF_ALL(:,:) => NULL()

!REAL (KIND=JPRB)   , POINTER :: PSTACK  (:,:)
REAL(KIND=JPRB), DIMENSION(:,:)     , POINTER  :: PSTACK_ALL => NULL ()

INTEGER :: ISTSZ, ISTPT

INTEGER :: ISTSZ_ALL, ISTPT_ALL

INTEGER :: IBL, JIDIA, JFDIA
LOGICAL :: LLDIFF, LLPRINT
CHARACTER (LEN=32) :: CLCASE
INTEGER :: ICOUNT1, KLON1, ICOUNT, KLON0, ICOUNT0, JLON
INTEGER, POINTER :: IDIFFBLOCK (:) => NULL ()
INTEGER, ALLOCATABLE :: IFDIA (:)
INTEGER :: IDUM
CHARACTER (LEN=64) :: CLFILE
LOGICAL :: LLONEBYONE

#include "achmt.intfb.h"


CALL INITOPTIONS ()
CALL GETOPTION ("--case", CLCASE, MND = .TRUE.)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--diff-block-list", IDIFFBLOCK)
ICOUNT1 = 0
CALL GETOPTION ("--count", ICOUNT1)
KLON1 = 0
CALL GETOPTION ("--nproma", KLON1)
CALL GETOPTION ("--onebyone", LLONEBYONE)
CALL CHECKOPTIONS ()

OPEN (77, FORM='FORMATTED', FILE=TRIM (CLCASE)//'/ACHMT.COUNT')
READ (77, *) ICOUNT
CLOSE (77)

ALLOCATE (IFDIA (ICOUNT))

CALL ACHMT_LOAD_ALL (TRIM (CLCASE)//'/ACHMT.CONST')
!CALL LOAD_YOMPHY
!CALL LOAD_YOMPHY0
!CALL LOAD_YOMPHY1
!CALL LOAD_YOMPHY2


CALL OPEN_LOAD (TRIM (CLCASE)//"/ACHMT")

IF (ICOUNT1 == 0) ICOUNT1 = ICOUNT

PRINT *, "-- READ"

DO IBL = 1, ICOUNT

  PRINT *, 'IBL=', IBL

  CALL LOAD (ILUN_IN, KLON)

  IF (KLON1 == 0) THEN
    KLON1 = KLON
    KFDIA = KLON
  ENDIF
  IFDIA (IBL) = KLON


  !CALL LOAD (ILUN_IN, KLON)
  CALL LOAD (ILUN_IN, KLEV)
  CALL LOAD (ILUN_IN, KIDIA)

  !KIDIA = 1

  CALL LOAD (ILUN_IN, KFDIA)

  !KFDIA = KLON

  CALL LOAD (ILUN_IN, LDZ0H)
  CALL LOAD (ILUN_IN, LDCLS)
  CALL LOAD (ILUN_IN, LDHMT)


!#define LOADA(x) CALL O (#x//".IN"); CALL LOAD (ILUN, x); CLOSE (ILUN); IDUM

!#define LOADA(x) CALL O (#x//".IN"); CALL LOAD (ILUN_IN, x); CLOSE (ILUN_IN); IDUM
!#define LOADA(x) CALL O ("ACHMT.IN"); CALL LOAD (ILUN_IN, x); CLOSE (ILUN_IN); IDUM

#define SET(x) CALL SETALL (x##_ALL)
  SET(PAPHI)
  SET(PAPHIF)
  SET(PAPRS)
  SET(PAPRSF)
  SET(PCP)
  SET(PQ)
  SET(PR)
  SET(PT)
  SET(PU)
  SET(PV)
  SET(PFPLSH)
  SET(PFPLCH)
  SET(PDPHIT)
  SET(PDPHIV)
  SET(PGZ0F)
  SET(PGZ0HF)
  SET(PGZ0RLF)
  SET(PHV)
  SET(PLSM)
  SET(PNEIJG)
  SET(PNEIJV)
  SET(PSNS)
  SET(PTS)
  SET(PVEG0)
  SET(PWFC)
  SET(PWS)
  SET(PWSI)
  SET(PNBVNO)
  SET(PMRIPP)
  SET(PCD)
  SET(PCDN)
  SET(PCDROV)
  SET(PCH)
  SET(PCHROV)
  SET(PCPS)
  SET(PDQSTS)
  SET(PGWDCS)
  SET(PGZ0)
  SET(PGZ0H)
  SET(PHQ)
  SET(PHU)
  SET(PNEIJ)
  SET(PQCLS)
  SET(PQS)
  SET(PQSATS)
  SET(PRHCLS)
  SET(PRS)
  SET(PRTI)
  SET(PSTAB)
  SET(PTCLS)
  SET(PUCLS)
  SET(PVCLS)
  SET(PUCLN)
  SET(PVCLN)
  SET(PZPCLS)
  SET(PVEG)
  SET(PXDROV)
  SET(PXHROV)
  SET(PURAF)
  SET(PVRAF)



ENDDO

!#undef LOADA
#undef SET

KLON0 = KLON; ICOUNT0 = ICOUNT
KLON = KLON1; ICOUNT = ICOUNT1

!KLEV = SIZE (PAPHIF_ALL, 2)
!KSV = SIZE (PSVM_ALL, 3)

ISTSZ = (40 * KLEV + 20) * KLON
ISTPT = 1

ISTSZ_ALL = ISTSZ
ISTPT_ALL = ISTPT

ALLOCATE (PSTACK_ALL (ISTSZ, ICOUNT))
!ALLOCATE (PSTACK (ISTSZ, ICOUNT))

IF (LLONEBYONE) THEN
!$OMP PARALLEL DO PRIVATE (IBL, JIDIA, JFDIA, JLON)

DO IBL = 1, ICOUNT
  DO JLON = 1, KLON
    JIDIA = JLON
    JFDIA = JLON


    CALL ACHMT (JIDIA,JFDIA,KLON,KLEV,LDZ0H,&
     PAPHI_ALL(:,:,IBL), PAPHIF_ALL(:,:,IBL), PAPRS_ALL(:,:,IBL),& 
     PAPRSF_ALL(:,:,IBL), PCP_ALL(:,:,IBL),PQ_ALL(:,:,IBL),      & 
     PR_ALL(:,:,IBL), PT_ALL(:,:,IBL), PU_ALL(:,:,IBL),          & 
     PV_ALL(:,:,IBL), PFPLSH_ALL(:,:,IBL), PFPLCH_ALL(:,:,IBL),  & 
     PDPHIT_ALL(:,IBL), PDPHIV_ALL(:,IBL), PGZ0F_ALL(:,IBL),     & 
     PGZ0HF_ALL(:,IBL), PGZ0RLF_ALL(:,IBL), PHV_ALL(:,IBL),      & 
     PLSM_ALL(:,IBL), PNEIJG_ALL(:,IBL), PNEIJV_ALL(:,IBL),      & 
     PSNS_ALL(:,IBL), PTS_ALL(:,IBL), PVEG0_ALL(:,IBL),          & 
     PWFC_ALL(:,IBL), PWS_ALL(:,IBL), PWSI_ALL(:,IBL),           & 
     LDCLS, LDHMT,                                   &
     PNBVNO_ALL(:,:,IBL), PMRIPP_ALL(:,:,IBL), PCD_ALL(:,IBL),   & 
     PCDN_ALL(:,IBL), PCDROV_ALL(:,IBL), PCH_ALL(:,IBL),         & 
     PCHROV_ALL(:,IBL), PCPS_ALL(:,IBL), PDQSTS_ALL(:,IBL),      & 
     PGWDCS_ALL(:,IBL), PGZ0_ALL(:,IBL), PGZ0H_ALL(:,IBL),       & 
     PHQ_ALL(:,IBL), PHU_ALL(:,IBL), PNEIJ_ALL(:,IBL),           & 
     PQCLS_ALL(:,IBL), PQS_ALL(:,IBL), PQSATS_ALL(:,IBL),        & 
     PRHCLS_ALL(:,IBL), PRS_ALL(:,IBL), PRTI_ALL(:,IBL),         & 
     PSTAB_ALL(:,IBL), PTCLS_ALL(:,IBL), PUCLS_ALL(:,IBL),       & 
     PVCLS_ALL(:,IBL), PUCLN_ALL(:,IBL), PVCLN_ALL(:,IBL),       & 
     PZPCLS_ALL(:,IBL), PVEG_ALL(:,IBL), PXDROV_ALL(:,IBL),      & 
     PXHROV_ALL(:,IBL), PURAF_ALL(:,IBL), PVRAF_ALL(:,IBL),      & 
     ISTPT, ISTSZ, PSTACK_ALL(:,IBL))
  ENDDO

ENDDO
!$OMP END PARALLEL DO

ELSE



!$acc parallel loop gang vector collapse (2) private (IBL, JLON, JIDIA, JFDIA) &
!$acc  & copy (PAPHI_ALL, PAPHIF_ALL, PAPRS_ALL,& 
!$acc  & PAPRSF_ALL, PCP_ALL,PQ_ALL,      & 
!$acc  & PR_ALL, PT_ALL, PU_ALL,          & 
!$acc  & PV_ALL, PFPLSH_ALL, PFPLCH_ALL,  & 
!$acc  & PDPHIT_ALL, PDPHIV_ALL, PGZ0F_ALL,     & 
!$acc  & PGZ0HF_ALL, PGZ0RLF_ALL, PHV_ALL,      & 
!$acc  & PLSM_ALL, PNEIJG_ALL, PNEIJV_ALL,      & 
!$acc  & PSNS_ALL, PTS_ALL, PVEG0_ALL,          & 
!$acc  & PWFC_ALL, PWS_ALL, PWSI_ALL,           & 
!$acc  & PNBVNO_ALL, PMRIPP_ALL, PCD_ALL,   & 
!$acc  & PCDN_ALL, PCDROV_ALL, PCH_ALL,         & 
!$acc  & PCHROV_ALL, PCPS_ALL, PDQSTS_ALL,      & 
!$acc  & PGWDCS_ALL, PGZ0_ALL, PGZ0H_ALL,       & 
!$acc  & PHQ_ALL, PHU_ALL, PNEIJ_ALL,           & 
!$acc  & PQCLS_ALL, PQS_ALL, PQSATS_ALL,        & 
!$acc  & PRHCLS_ALL, PRS_ALL, PRTI_ALL,         & 
!$acc  & PSTAB_ALL, PTCLS_ALL, PUCLS_ALL,       & 
!$acc  & PVCLS_ALL, PUCLN_ALL, PVCLN_ALL,       & 
!$acc  & PZPCLS_ALL, PVEG_ALL, PXDROV_ALL,      & 
!$acc  & PXHROV_ALL, PURAF_ALL, PVRAF_ALL,      & 
!$acc  & PSTACK_ALL)

DO IBL = 1, ICOUNT1

    DO JLON = 1, KLON

    JIDIA = JLON
    JFDIA = JLON

    CALL ACHMT (JIDIA,JFDIA,KLON,KLEV,LDZ0H,&
     PAPHI_ALL(:,:,IBL), PAPHIF_ALL(:,:,IBL), PAPRS_ALL(:,:,IBL),& 
     PAPRSF_ALL(:,:,IBL), PCP_ALL(:,:,IBL),PQ_ALL(:,:,IBL),      & 
     PR_ALL(:,:,IBL), PT_ALL(:,:,IBL), PU_ALL(:,:,IBL),          & 
     PV_ALL(:,:,IBL), PFPLSH_ALL(:,:,IBL), PFPLCH_ALL(:,:,IBL),  & 
     PDPHIT_ALL(:,IBL), PDPHIV_ALL(:,IBL), PGZ0F_ALL(:,IBL),     & 
     PGZ0HF_ALL(:,IBL), PGZ0RLF_ALL(:,IBL), PHV_ALL(:,IBL),      & 
     PLSM_ALL(:,IBL), PNEIJG_ALL(:,IBL), PNEIJV_ALL(:,IBL),      & 
     PSNS_ALL(:,IBL), PTS_ALL(:,IBL), PVEG0_ALL(:,IBL),          & 
     PWFC_ALL(:,IBL), PWS_ALL(:,IBL), PWSI_ALL(:,IBL),           & 
     LDCLS, LDHMT,                                   &
     PNBVNO_ALL(:,:,IBL), PMRIPP_ALL(:,:,IBL), PCD_ALL(:,IBL),   & 
     PCDN_ALL(:,IBL), PCDROV_ALL(:,IBL), PCH_ALL(:,IBL),         & 
     PCHROV_ALL(:,IBL), PCPS_ALL(:,IBL), PDQSTS_ALL(:,IBL),      & 
     PGWDCS_ALL(:,IBL), PGZ0_ALL(:,IBL), PGZ0H_ALL(:,IBL),       & 
     PHQ_ALL(:,IBL), PHU_ALL(:,IBL), PNEIJ_ALL(:,IBL),           & 
     PQCLS_ALL(:,IBL), PQS_ALL(:,IBL), PQSATS_ALL(:,IBL),        & 
     PRHCLS_ALL(:,IBL), PRS_ALL(:,IBL), PRTI_ALL(:,IBL),         & 
     PSTAB_ALL(:,IBL), PTCLS_ALL(:,IBL), PUCLS_ALL(:,IBL),       & 
     PVCLS_ALL(:,IBL), PUCLN_ALL(:,IBL), PVCLN_ALL(:,IBL),       & 
     PZPCLS_ALL(:,IBL), PVEG_ALL(:,IBL), PXDROV_ALL(:,IBL),      & 
     PXHROV_ALL(:,IBL), PURAF_ALL(:,IBL), PVRAF_ALL(:,IBL),      & 
     ISTPT, ISTSZ, PSTACK_ALL(:,IBL))

     ENDDO

ENDDO
!$acc end parallel loop


ENDIF



IF (LLDIFF .AND. KLON0 == KLON1) THEN

PRINT *, "-- DIFF"

DO IBL = 1, ICOUNT0

  LLPRINT = .TRUE.
  IF (ASSOCIATED (IDIFFBLOCK)) THEN
    IF (.NOT. ANY (IDIFFBLOCK == IBL)) LLPRINT = .FALSE.
  ENDIF

  IF (LLPRINT) PRINT *, " BLOCK = ", IBL

#define DIFF(x) CALL DDIFF (#x, x##_ALL, LLPRINT)
  !PRINT *, 'PNBVNO = ', PNBVNO
  !PRINT *, 'PNBVNO_ALL = ', PNBVNO_ALL
  DIFF(PNBVNO)
  DIFF(PMRIPP)
  DIFF(PCD)
  DIFF(PCDN)
  DIFF(PCDROV)
  DIFF(PCH)
  DIFF(PCHROV)
  DIFF(PCPS)
  DIFF(PDQSTS)
  DIFF(PGWDCS)
  DIFF(PGZ0)
  DIFF(PGZ0H)
  DIFF(PHQ)
  DIFF(PHU)
  DIFF(PNEIJ)
  DIFF(PQCLS)
  DIFF(PQS)
  DIFF(PQSATS)
  DIFF(PRHCLS)
  DIFF(PRS)
  DIFF(PRTI)
  DIFF(PSTAB)
  DIFF(PTCLS)
  DIFF(PUCLS)
  DIFF(PVCLS)
  DIFF(PUCLN)
  DIFF(PVCLN)
  DIFF(PZPCLS)
  DIFF(PVEG)
  DIFF(PXDROV)
  DIFF(PXHROV)
  DIFF(PURAF)
  DIFF(PVRAF)
  


#undef DIFF

ENDDO

ENDIF


CALL CLOSE_LOAD

CONTAINS

#include "contains.h"

SUBROUTINE O (CDFILE)

INTEGER, PARAMETER :: MYPROC = 1

CHARACTER (LEN=*) :: CDFILE

WRITE (CLFILE, '(I3.3)') MYPROC
CLFILE=TRIM (CDFILE)//"."//TRIM (CLFILE)
OPEN (ILUN_IN, FILE=TRIM (CLCASE)//"/"//TRIM (CLFILE), FORM='UNFORMATTED')

END SUBROUTINE

END

